# Change these first
owner: AdamGalt # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: galt.me
    url: https://galt.me
  - name: blog.galt.me
    url: https://blog.galt.me
  - name: tv.galt.me
    url: https://tv.galt.me
  - name: music.galt.me
    url: https://music.galt.me
  - name: screen.galt.me
    url: https://screen.galt.me
  - name: text.galt.me
    url: https://text.galt.me
  - name: code.galt.me
    url: https://code.galt.me
  - name: speed.galt.me
    url: https://speed.galt.me
  - name: Google
    url: https://www.google.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.galt.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a service status page. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
